name: CDK Deploy SalahSlotsCalendar

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: infrastructure/package-lock.json

      - name: Install Lambda dependencies
        run: |
          cd src/lambda/SalahSlotsCalendar
          npm ci

      - name: Run Jest for Lambda tests
        run: |
          cd src/lambda/SalahSlotsCalendar
          npm run test

      - name: build 
        run: |
          cd src/lambda/SalahSlotsCalendar
          npm run build

      - name: Install CDK and dependencies
        run: |
          npm install -g aws-cdk
          cd infrastructure
          npm ci

      - name: run CDK tests
        run: |
          cd infrastructure
          npm run test

      - name: Synthesize CDK Stack
        run: |
          cd infrastructure
          npx cdk synth

      - name: Deploy CDK Stack
        run: |
          cd infrastructure
          npx cdk deploy --require-approval never
        env:
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

